'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { clsx } from 'clsx'
import { useLocale } from '@/lib/i18n/LocaleProvider'
import { Sparkline } from '@/components/ui/Sparkline'
import { RotatingGlobe } from '@/components/marketing/RotatingGlobe'
import { HeroSpaceBackground } from '@/components/marketing/HeroSpaceBackground'

interface QuoteItem {
  symbol: string
  price: number | null
  changePct: number | null
}
interface QuoteResponse {
  quotes: QuoteItem[]
}
interface HistoryPoint {
  close: number
}

const HERO_SYMBOLS = ['SPX500', 'XAUUSD', 'VIX']

const COPY = {
  en: {
    breadcrumb: 'TRADING / ALGORITHMS / MARKETS',
    h1a: 'Decisions built on data,',
    h1b: 'not emotion.',
    sub: 'Quantum Traders OS is a market intelligence terminal that gives you context, signals, and tools to trade with more clarity, precision, and discipline.',
    ctaPrimary: 'ENTER THE TERMINAL',
    ctaSecondary: 'SEE THE PLATFORM',
    login: 'LOG IN',
    globalMarkets: 'GLOBAL MARKETS',
    live: 'LIVE',
    features: [
      { title: 'MARKET ANALYSIS', desc: 'Macro context, regime, volatility and opportunities in real time.' },
      { title: 'ANALYSIS TOOLS', desc: 'Scanner, charts, correlations, gamma and more.' },
      { title: 'RISK MANAGEMENT', desc: 'Calculators, exposure, limits and capital control.' },
      { title: 'TRADE JOURNAL', desc: 'Audit your execution, spot patterns and keep improving.' },
      { title: 'EDUCATION', desc: 'From the basics to advanced and algorithmic trading.' },
    ],
    showcase: {
      command: 'COMMAND', markets: 'MARKETS', risk: 'RISK', tools: 'TOOLS', journal: 'JOURNAL', learn: 'LEARN', account: 'ACCOUNT',
      marketState: 'MARKET STATE',
      regime: 'Regime', volatility: 'Volatility', bias: 'Bias', drawdown: 'Drawdown',
      trending: 'Trending', bullish: 'Bullish',
      keyMarkets: 'KEY MARKETS', symbol: 'SYMBOL', price: 'PRICE', change: 'CHANGE', rgm: 'REGIME', rs: 'RS',
      topOpportunities: 'TOP OPPORTUNITIES', viewAll: 'View all opportunities →',
      upcomingEvents: 'UPCOMING EVENTS', viewCalendar: 'View full calendar →',
      aiBrief: 'AI MARKET BRIEF', generated: 'Generated by AI', conf: 'Conf.',
      briefText: 'US indices hold a slight bullish bias short-term. Volatility stays contained while XAUUSD shows relative strength. Macro context remains favorable for risk assets, watch inflation data.',
    },
    advantage: {
      kicker: 'YOUR EDGE',
      title: 'Real information. In one place.',
      desc: 'Quantum Traders OS combines market intelligence, technical analysis and risk management tools so you make better decisions, faster.',
      stats: [
        { value: '6', label: 'CORE MARKETS' },
        { value: '24/7', label: 'REAL-TIME ANALYSIS' },
        { value: '1', label: 'TERMINAL, ALL-IN-ONE' },
      ],
      tagline: "THE MARKET DOESN'T WAIT. NEITHER DO YOU.",
    },
  },
  es: {
    breadcrumb: 'TRADING / ALGORITMOS / MERCADOS',
    h1a: 'Decisiones basadas',
    h1b: 'en datos, no en emociones.',
    sub: 'Quantum Traders OS es un terminal de inteligencia de mercado que te da el contexto, las señales y las herramientas para operar con mayor claridad, precisión y disciplina.',
    ctaPrimary: 'ACCEDER AL TERMINAL',
    ctaSecondary: 'CONOCE LA PLATAFORMA',
    login: 'INGRESAR',
    globalMarkets: 'GLOBAL MARKETS',
    live: 'LIVE',
    features: [
      { title: 'ANÁLISIS DE MERCADO', desc: 'Contexto macro, régimen, volatilidad y oportunidades en tiempo real.' },
      { title: 'HERRAMIENTAS DE ANÁLISIS', desc: 'Scanner, gráficos, correlaciones, gamma y más.' },
      { title: 'GESTIÓN DE RIESGO', desc: 'Calculadoras, exposición, límites y control de capital.' },
      { title: 'REGISTRO DE TRADES', desc: 'Analiza tu ejecución, identifica patrones y mejora continuamente.' },
      { title: 'EDUCACIÓN', desc: 'Desde lo básico hasta estrategias avanzadas y trading algorítmico.' },
    ],
    showcase: {
      command: 'COMMAND', markets: 'MARKETS', risk: 'RISK', tools: 'TOOLS', journal: 'JOURNAL', learn: 'LEARN', account: 'ACCOUNT',
      marketState: 'MARKET STATE',
      regime: 'Regime', volatility: 'Volatility', bias: 'Bias', drawdown: 'Drawdown',
      trending: 'Trending', bullish: 'Bullish',
      keyMarkets: 'KEY MARKETS', symbol: 'SYMBOL', price: 'PRICE', change: 'CHANGE', rgm: 'REGIME', rs: 'RS',
      topOpportunities: 'TOP OPORTUNIDADES', viewAll: 'Ver todas las oportunidades →',
      upcomingEvents: 'PRÓXIMOS EVENTOS', viewCalendar: 'Ver calendario completo →',
      aiBrief: 'AI MARKET BRIEF', generated: 'Generado por IA', conf: 'Conf.',
      briefText: 'Los índices de EE.UU. mantienen un sesgo positivo a corto plazo. La volatilidad se mantiene estable mientras XAUUSD muestra fuerza relativa. El contexto macro sigue siendo favorable para activos de riesgo, con atención a los datos de inflación.',
    },
    advantage: {
      kicker: 'TU VENTAJA',
      title: 'Información real. En un solo lugar.',
      desc: 'Quantum Traders OS combina inteligencia de mercado, análisis técnico y herramientas de gestión para que tomes mejores decisiones, más rápido.',
      stats: [
        { value: '6', label: 'MERCADOS PRINCIPALES' },
        { value: '24/7', label: 'ANÁLISIS EN TIEMPO REAL' },
        { value: '1', label: 'TERMINAL TODO EN UNO' },
      ],
      tagline: 'EL MERCADO NO ESPERA. TU TAMPOCO.',
    },
  },
} as const

function GridIcon({ cls }: { cls: string }) {
  return (
    <svg className={cls} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
      <rect x="3.75" y="3.75" width="7" height="7" rx="1.5" />
      <rect x="13.25" y="3.75" width="7" height="7" rx="1.5" />
      <rect x="3.75" y="13.25" width="7" height="7" rx="1.5" />
      <rect x="13.25" y="13.25" width="7" height="7" rx="1.5" />
    </svg>
  )
}
function ChartIcon({ cls }: { cls: string }) {
  return (
    <svg className={cls} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
      <path strokeLinecap="round" strokeLinejoin="round" d="M3 17l5-5 4 4 8-9M20 7v5h-5" />
    </svg>
  )
}
function ShieldIcon({ cls }: { cls: string }) {
  return (
    <svg className={cls} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
      <path strokeLinecap="round" strokeLinejoin="round" d="M12 3l7 3v5c0 4.5-3 8-7 10-4-2-7-5.5-7-10V6l7-3z" />
    </svg>
  )
}
function DocIcon({ cls }: { cls: string }) {
  return (
    <svg className={cls} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
      <path strokeLinecap="round" strokeLinejoin="round" d="M7 3.75h7l3.25 3.25v13a1 1 0 01-1 1H7a1 1 0 01-1-1V4.75a1 1 0 011-1z" />
      <path strokeLinecap="round" strokeLinejoin="round" d="M9 12h6M9 15.5h6M9 8.5h3" />
    </svg>
  )
}
function BookIcon({ cls }: { cls: string }) {
  return (
    <svg className={cls} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
      <path strokeLinecap="round" strokeLinejoin="round" d="M4 5.5C4 4.67 4.67 4 5.5 4H12v16H5.5A1.5 1.5 0 014 18.5v-13zM20 5.5c0-.83-.67-1.5-1.5-1.5H12v16h6.5a1.5 1.5 0 001.5-1.5v-13z" />
    </svg>
  )
}

const FEATURE_ICONS = [GridIcon, ChartIcon, ShieldIcon, DocIcon, BookIcon]

function HeroDataCard({ symbol, quote, history, unit }: { symbol: string; quote: QuoteItem | undefined; history: number[]; unit?: boolean }) {
  const up = (quote?.changePct ?? 0) >= 0
  return (
    <div className="rounded-xl border border-bg-border bg-bg-card/95 backdrop-blur-sm px-4 py-3 shadow-lg space-y-1.5 w-[150px]">
      <p className="text-[10px] font-mono text-ink-dim font-bold">{symbol}</p>
      <p className={clsx('text-sm font-mono font-bold', unit ? 'text-ink-primary' : up ? 'text-atlas' : 'text-bear')}>
        {unit ? `${quote?.price?.toFixed(1) ?? '—'}` : `${quote?.changePct !== null && quote?.changePct !== undefined ? `${up ? '+' : ''}${quote.changePct.toFixed(2)}%` : '—'}`}
      </p>
      <Sparkline values={history} up={up} />
    </div>
  )
}

export function LandingPage() {
  const { locale, setLocale } = useLocale()
  const t = COPY[locale]
  const [quotes, setQuotes] = useState<Record<string, QuoteItem>>({})
  const [histories, setHistories] = useState<Record<string, number[]>>({})

  useEffect(() => {
    let mounted = true
    const load = async () => {
      try {
        const [quotePayload, ...historyPayloads] = await Promise.all([
          fetch(`/api/market/quote?symbols=${HERO_SYMBOLS.join(',')}`).then((r) => r.json() as Promise<QuoteResponse>),
          ...HERO_SYMBOLS.map((s) => fetch(`/api/market/history?symbol=${s}&interval=1h&outputsize=24`).then((r) => r.json() as Promise<HistoryPoint[]>)),
        ])
        if (!mounted) return
        const qMap: Record<string, QuoteItem> = {}
        for (const item of quotePayload?.quotes ?? []) qMap[item.symbol] = item
        setQuotes(qMap)
        const hMap: Record<string, number[]> = {}
        HERO_SYMBOLS.forEach((s, i) => {
          hMap[s] = (Array.isArray(historyPayloads[i]) ? historyPayloads[i] : []).map((c) => c.close).filter((v): v is number => Number.isFinite(v))
        })
        setHistories(hMap)
      } catch {
        // hero cards just show placeholders on failure — no fake numbers
      }
    }
    load()
  }, [])

  return (
    <div className="min-h-screen bg-bg-base text-ink-primary overflow-x-hidden">
      {/* ── Nav ── */}
      <header className="flex items-center justify-between px-6 md:px-10 py-5 border-b border-bg-border">
        <div className="flex items-center gap-3">
          <div className="relative flex items-center justify-center w-9 h-9 rounded-md bg-oracle-dim border border-oracle/25">
            <span className="text-oracle text-xs font-mono font-bold">QT</span>
          </div>
          <div className="leading-none">
            <p className="text-[11px] font-mono font-bold tracking-[0.18em] uppercase">Quantum Traders OS</p>
            <p className="text-[8px] font-mono text-ink-dim tracking-[0.18em] uppercase mt-0.5">Market Intelligence Terminal</p>
          </div>
        </div>
        <div className="flex items-center gap-3">
          <div className="hidden sm:flex items-center gap-1 mr-2">
            {(['es', 'en'] as const).map((code) => (
              <button
                key={code}
                type="button"
                onClick={() => setLocale(code)}
                className={clsx(
                  'px-2 py-1 rounded text-[9px] font-mono font-semibold uppercase transition-colors',
                  locale === code ? 'bg-oracle/15 text-oracle border border-oracle/30' : 'text-ink-dim hover:text-ink-muted border border-transparent',
                )}
              >
                {code}
              </button>
            ))}
          </div>
          <Link
            href="/login"
            className="px-4 py-2 rounded-lg border border-oracle/30 bg-transparent text-ink-primary text-[10px] font-mono font-bold uppercase tracking-wider hover:bg-oracle/10 transition-colors"
          >
            {t.login}
          </Link>
        </div>
      </header>

      {/* ── Hero ── */}
      <section className="relative isolate py-16 overflow-hidden">
        <div className="absolute inset-0 -z-10">
          <HeroSpaceBackground />
        </div>
        <div className="absolute inset-x-0 bottom-0 h-24 -z-10 bg-gradient-to-b from-transparent to-bg-base" />
        <div className="max-w-[1400px] mx-auto px-6 md:px-10 w-full grid grid-cols-1 xl:grid-cols-[1fr_1fr] gap-12 items-center">
          <div>
            <p className="text-[10px] font-mono text-ink-dim uppercase tracking-[0.25em]">{t.breadcrumb}</p>
            <h1 className="font-display text-4xl sm:text-5xl font-bold tracking-tight leading-[1.15] mt-5 text-ink-primary">
              {t.h1a}
              <br />
              <span className="text-oracle">{t.h1b}</span>
            </h1>
            <p className="text-sm font-mono text-ink-muted mt-6 max-w-md leading-relaxed">{t.sub}</p>
            <div className="flex flex-wrap items-center gap-6 mt-9">
              <Link
                href="/login"
                className="px-6 py-3.5 rounded-lg bg-oracle text-white text-xs font-mono font-bold uppercase tracking-widest hover:bg-oracle/90 transition-colors inline-flex items-center gap-2"
              >
                {t.ctaPrimary} →
              </Link>
              <a href="#showcase" className="text-xs font-mono font-bold uppercase tracking-widest text-ink-secondary hover:text-ink-primary transition-colors inline-flex items-center gap-2">
                <span className="w-6 h-6 rounded-full border border-bg-border flex items-center justify-center">▶</span>
                {t.ctaSecondary}
              </a>
            </div>
          </div>

          {/* Globe + floating live cards */}
          <div className="relative h-[420px] hidden xl:block">
            <div className="absolute inset-0 flex items-center justify-center">
              <div className="w-[380px] h-[380px]">
                <RotatingGlobe size={380} />
              </div>
            </div>
            <div className="absolute top-2 right-4 flex items-center gap-2 px-3 py-1.5 rounded-lg border border-bg-border bg-bg-card/90 backdrop-blur-sm">
              <span className="text-[9px] font-mono text-ink-dim uppercase tracking-wider">{t.globalMarkets}</span>
              <span className="flex items-center gap-1 text-[9px] font-mono text-atlas font-bold uppercase">
                <span className="w-1.5 h-1.5 rounded-full bg-atlas animate-pulse-slow" /> {t.live}
              </span>
            </div>
            <div className="absolute top-24 left-0">
              <HeroDataCard symbol="SPX500" quote={quotes.SPX500} history={histories.SPX500 ?? []} />
            </div>
            <div className="absolute top-44 right-0">
              <HeroDataCard symbol="XAUUSD" quote={quotes.XAUUSD} history={histories.XAUUSD ?? []} />
            </div>
            <div className="absolute bottom-6 left-10">
              <HeroDataCard symbol="VIX" quote={quotes.VIX} history={histories.VIX ?? []} unit />
            </div>
          </div>
        </div>
      </section>

      {/* ── Feature grid ── */}
      <section className="max-w-[1400px] mx-auto px-6 md:px-10 py-14 border-t border-bg-border grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-8">
        {t.features.map((feature, i) => {
          const Icon = FEATURE_ICONS[i]
          return (
            <div key={feature.title} className="space-y-3">
              <div className="w-11 h-11 rounded-lg border border-oracle/30 bg-oracle/8 flex items-center justify-center">
                <Icon cls="w-5 h-5 text-oracle" />
              </div>
              <p className="text-xs font-mono font-bold text-ink-primary tracking-wide">{feature.title}</p>
              <p className="text-[11px] font-mono text-ink-dim leading-relaxed">{feature.desc}</p>
            </div>
          )
        })}
      </section>

      {/* ── Product showcase ── */}
      <section id="showcase" className="max-w-[1400px] mx-auto px-6 md:px-10 py-16 border-t border-bg-border grid grid-cols-1 lg:grid-cols-[1.4fr_1fr] gap-12 items-center">
        <div className="rounded-2xl border border-bg-border bg-bg-card overflow-hidden shadow-2xl">
          <div className="flex">
            {/* mini sidebar */}
            <div className="w-32 shrink-0 border-r border-bg-border bg-bg-deep p-3 space-y-3 hidden sm:block">
              <div className="flex items-center gap-1.5 pb-2 border-b border-bg-border">
                <div className="w-5 h-5 rounded bg-oracle-dim border border-oracle/25 flex items-center justify-center">
                  <span className="text-oracle text-[7px] font-mono font-bold">QT</span>
                </div>
                <span className="text-[7px] font-mono text-ink-dim uppercase tracking-wider">Quantum</span>
              </div>
              {[t.showcase.command, t.showcase.markets, t.showcase.risk, t.showcase.tools, t.showcase.journal, t.showcase.learn, t.showcase.account].map((label, i) => (
                <p key={label} className={clsx('text-[8px] font-mono uppercase tracking-wider px-1.5 py-1 rounded', i === 0 ? 'bg-bg-elevated text-ink-primary font-bold' : 'text-ink-dim')}>
                  {label}
                </p>
              ))}
            </div>

            {/* mini command view */}
            <div className="flex-1 p-4 space-y-3">
              <div className="flex items-center justify-between">
                <span className="text-[9px] font-mono font-bold text-ink-primary uppercase tracking-wider">{t.showcase.marketState}</span>
                <span className="text-[8px] font-mono text-atlas uppercase px-1.5 py-0.5 rounded bg-atlas/10 border border-atlas/25">Risk-On 86</span>
              </div>

              <div className="grid grid-cols-4 gap-2">
                {[
                  [t.showcase.regime, t.showcase.trending, 'text-oracle'],
                  [t.showcase.volatility, 'VIX 16.8', 'text-ink-primary'],
                  [t.showcase.bias, t.showcase.bullish, 'text-atlas'],
                  [t.showcase.drawdown, '-2.8%', 'text-bear'],
                ].map(([label, value, color]) => (
                  <div key={label} className="rounded-lg border border-bg-border bg-bg-elevated/20 p-2">
                    <p className="text-[7px] font-mono text-ink-dim uppercase">{label}</p>
                    <p className={clsx('text-[9px] font-mono font-bold mt-0.5', color)}>{value}</p>
                  </div>
                ))}
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div className="rounded-lg border border-bg-border bg-bg-elevated/10 p-2.5 space-y-1.5">
                  <p className="text-[7px] font-mono text-ink-dim uppercase tracking-wider">{t.showcase.keyMarkets}</p>
                  {[
                    ['SPX500', '5,612.4', '+0.42%', true],
                    ['NAS100', '19,842.7', '+0.63%', true],
                    ['XAUUSD', '2,624.8', '+0.55%', true],
                  ].map(([sym, price, chg, up]) => (
                    <div key={sym as string} className="flex items-center justify-between text-[8px] font-mono">
                      <span className="text-ink-primary font-bold">{sym}</span>
                      <span className="text-ink-secondary">{price}</span>
                      <span className={up ? 'text-atlas' : 'text-bear'}>{chg}</span>
                    </div>
                  ))}
                </div>
                <div className="rounded-lg border border-bg-border bg-bg-elevated/10 p-2.5 space-y-1.5">
                  <p className="text-[7px] font-mono text-ink-dim uppercase tracking-wider">{t.showcase.topOpportunities}</p>
                  {[
                    ['SPX500', 'Bullish', '0.72'],
                    ['NAS100', 'Bullish', '0.64'],
                    ['XAUUSD', 'Bullish', '0.58'],
                  ].map(([sym, tag, score]) => (
                    <div key={sym as string} className="flex items-center justify-between text-[8px] font-mono">
                      <span className="text-ink-primary font-bold">{sym}</span>
                      <span className="text-atlas">{tag}</span>
                      <span className="text-ink-secondary">{score}</span>
                    </div>
                  ))}
                </div>
              </div>

              <div className="rounded-lg border border-oracle/25 bg-oracle/5 p-2.5 space-y-1">
                <p className="text-[7px] font-mono text-oracle uppercase tracking-wider font-bold">{t.showcase.aiBrief}</p>
                <p className="text-[8px] font-mono text-ink-secondary leading-relaxed line-clamp-2">{t.showcase.briefText}</p>
              </div>
            </div>
          </div>
        </div>

        <div className="space-y-6">
          <p className="text-[10px] font-mono text-oracle uppercase tracking-[0.25em] font-bold">{t.advantage.kicker}</p>
          <h2 className="font-display text-3xl font-bold text-ink-primary leading-tight">{t.advantage.title}</h2>
          <p className="text-sm font-mono text-ink-muted leading-relaxed max-w-md">{t.advantage.desc}</p>
          <div className="flex items-center gap-8">
            {t.advantage.stats.map((stat) => (
              <div key={stat.label}>
                <p className="text-2xl font-mono font-bold text-ink-primary">{stat.value}</p>
                <p className="text-[9px] font-mono text-ink-dim uppercase tracking-wider mt-1 max-w-[90px]">{stat.label}</p>
              </div>
            ))}
          </div>
          <div className="border-t border-bg-border pt-5">
            <p className="text-[10px] font-mono text-ink-secondary uppercase tracking-[0.2em] font-bold">{t.advantage.tagline}</p>
          </div>
        </div>
      </section>
    </div>
  )
}
